import { Buffer } from 'node:buffer';
import type { Env, KVNamespaceLike, R2BucketLike } from './env';
import { jsonResponse } from './http';
import {
  LEAD_FIELDS,
  LEAD_FORM_LABEL,
  LEAD_THANK_YOU_PATH,
  REQUIRED_LEAD_FIELDS,
  isLeadFormName,
  type LeadFormName,
} from './leadSchema';
import { isEmailAddress, readLeadMailConfig, type MailConfig } from './mailConfig';
import { readSiteOrigin } from './paymentConfig';
import { RATE_LIMITS, enforceRateLimit } from './rateLimit';
import { escapeHtml, type MailMessage, type SendMail } from './resend';
import { isSameOriginRequest } from './uploadCore';

/*
 * POST /api/lead — replacement for Netlify Forms.
 *
 * Order of operations is the contract:
 * 1. validate, 2. store the submission as JSON in R2 (the durable record),
 * 3. send the sales notification + customer confirmation via Resend.
 * The client gets success only if step 2 succeeded. A Resend failure is
 * logged and reported as `notified: false`, but the lead is kept.
 */

export const MAX_LEAD_BODY_BYTES = 64 * 1024;
const MAX_FILE_LINKS = 8;
const HONEYPOT_FIELD = 'bot-field';

// Retrieval links are generated by /api/uploads/complete; only that exact
// shape is accepted so the client cannot inject arbitrary links into e-mails.
const FILE_LINK_PATH_PATTERN =
  /^\/datei-abruf\/\?d=\d{4}-\d{2}-\d{2}&u=[0-9a-f-]{36}&f=[0-9a-f-]{36}&e=\d{1,12}&s=[A-Za-z0-9_-]{43}$/;

const SALES_STEPS = [
  'Eingangsbestätigung',
  'Technische Machbarkeitsprüfung',
  'Rückfragen zu Material, Stückzahl und Termin',
  'Angebot mit Lieferfenster',
];

export interface LeadFileLink {
  name: string;
  size: number | null;
  path: string;
}

export interface LeadRecord {
  id: string;
  receivedAt: string;
  form: LeadFormName;
  fields: Record<string, string>;
  fileLinks: LeadFileLink[];
  /** Fields that exceeded their length cap and were cut. */
  truncatedFields: string[];
}

export interface LeadDeps {
  env: Env;
  bucket: R2BucketLike;
  kv: KVNamespaceLike;
  sendMail: SendMail;
  now: () => Date;
  newId: () => string;
}

export function leadObjectKey(id: string, receivedAt: Date): string {
  const year = receivedAt.getUTCFullYear();
  const month = String(receivedAt.getUTCMonth() + 1).padStart(2, '0');
  return `leads/${year}/${month}/${id}.json`;
}

export function toFileLinks(value: unknown): LeadFileLink[] {
  if (!Array.isArray(value)) {
    return [];
  }
  return value
    .slice(0, MAX_FILE_LINKS)
    .filter(
      (item): item is { name: string; path: string; size?: unknown } =>
        typeof item === 'object' && item !== null && typeof item.name === 'string' && typeof item.path === 'string',
    )
    .filter((item) => FILE_LINK_PATH_PATTERN.test(item.path))
    .map((item) => ({
      name: item.name.trim().slice(0, 180),
      size: typeof item.size === 'number' && Number.isFinite(item.size) ? item.size : null,
      path: item.path,
    }));
}

type RawLead = { values: Record<string, unknown>; fileLinks: unknown; nativeForm: boolean };

type ParseResult = { ok: true; raw: RawLead } | { ok: false; response: Response };

async function parseBody(request: Request): Promise<ParseResult> {
  const declared = request.headers.get('content-length');
  if (declared !== null && /^\d+$/.test(declared) && Number(declared) > MAX_LEAD_BODY_BYTES) {
    return { ok: false, response: jsonResponse(413, { error: 'Anfrage zu groß.' }) };
  }
  const text = await request.text();
  if (Buffer.byteLength(text, 'utf8') > MAX_LEAD_BODY_BYTES) {
    return { ok: false, response: jsonResponse(413, { error: 'Anfrage zu groß.' }) };
  }
  const contentType = (request.headers.get('content-type') ?? '').toLowerCase();
  if (contentType.startsWith('application/json')) {
    let parsed: unknown;
    try {
      parsed = JSON.parse(text);
    } catch {
      return { ok: false, response: jsonResponse(400, { error: 'Ungültige Anfrage.' }) };
    }
    if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
      return { ok: false, response: jsonResponse(400, { error: 'Ungültige Anfrage.' }) };
    }
    const { file_links: fileLinks, ...values } = parsed as Record<string, unknown>;
    return { ok: true, raw: { values, fileLinks, nativeForm: false } };
  }
  if (contentType.startsWith('application/x-www-form-urlencoded')) {
    const values: Record<string, unknown> = {};
    new URLSearchParams(text).forEach((value, key) => {
      values[key] = value;
    });
    const acceptsHtml = (request.headers.get('accept') ?? '').includes('text/html');
    return { ok: true, raw: { values, fileLinks: [], nativeForm: acceptsHtml } };
  }
  return { ok: false, response: jsonResponse(415, { error: 'Nicht unterstütztes Format.' }) };
}

type ValidationResult =
  | { ok: true; form: LeadFormName; fields: Record<string, string>; truncatedFields: string[] }
  | { ok: false; error: string };

export function validateLead(values: Record<string, unknown>): ValidationResult {
  const form = values['form-name'] ?? values.form_name;
  if (!isLeadFormName(form)) {
    return { ok: false, error: 'Unbekanntes Formular.' };
  }
  const fields: Record<string, string> = {};
  const truncatedFields: string[] = [];
  for (const spec of LEAD_FIELDS) {
    const value = values[spec.name];
    if (typeof value !== 'string') {
      continue;
    }
    const trimmed = value.trim();
    if (trimmed === '') {
      continue;
    }
    if (trimmed.length > spec.maxLength) {
      fields[spec.name] = trimmed.slice(0, spec.maxLength);
      truncatedFields.push(spec.name);
    } else {
      fields[spec.name] = trimmed;
    }
  }
  for (const required of REQUIRED_LEAD_FIELDS) {
    if (!fields[required]) {
      return { ok: false, error: 'Bitte füllen Sie alle Pflichtfelder aus.' };
    }
  }
  fields.email = fields.email.toLowerCase();
  if (!isEmailAddress(fields.email) || truncatedFields.includes('email')) {
    return { ok: false, error: 'Bitte geben Sie eine gültige E-Mail-Adresse an.' };
  }
  return { ok: true, form, fields, truncatedFields };
}

function fileLinkHref(link: LeadFileLink, siteOrigin: string | null): string | null {
  return siteOrigin ? `${siteOrigin}${link.path}` : null;
}

export function buildLeadMails(
  record: LeadRecord,
  storageKey: string,
  mail: MailConfig,
  siteOrigin: string | null,
): { sales: MailMessage; customer: MailMessage } {
  const formLabel = LEAD_FORM_LABEL[record.form];
  const rows = LEAD_FIELDS.filter((spec) => record.fields[spec.name] !== undefined).map(
    (spec) => [spec.label, record.fields[spec.name]] as const,
  );
  const fileRows = record.fileLinks.map((link) => {
    const sizeLabel = link.size === null ? '' : ` (${(link.size / 1024 / 1024).toFixed(1)} MB)`;
    return { link, sizeLabel, href: fileLinkHref(link, siteOrigin) };
  });

  const salesHtml = [
    `<p><strong>Neuer Lead eingegangen (${escapeHtml(formLabel)})</strong></p>`,
    '<table cellpadding="4" cellspacing="0" border="0">',
    ...rows.map(
      ([label, value]) =>
        `<tr><td valign="top"><strong>${escapeHtml(label)}</strong></td><td>${escapeHtml(value).replace(/\n/g, '<br />')}</td></tr>`,
    ),
    '</table>',
    fileRows.length > 0
      ? `<p><strong>Datei-Download (signierte Links)</strong></p><ul>${fileRows
          .map(({ link, sizeLabel, href }) =>
            href
              ? `<li><a href="${escapeHtml(href)}">${escapeHtml(link.name)}</a>${escapeHtml(sizeLabel)}</li>`
              : `<li>${escapeHtml(link.name)} – ${escapeHtml(link.path)}${escapeHtml(sizeLabel)}</li>`,
          )
          .join('')}</ul>`
      : '',
    record.truncatedFields.length > 0
      ? `<p>Gekürzte Felder: ${escapeHtml(record.truncatedFields.join(', '))}</p>`
      : '',
    `<p>Lead-ID: ${escapeHtml(record.id)}<br />Gespeichert in R2: ${escapeHtml(storageKey)}</p>`,
    '<p><strong>Vertriebsstatus:</strong> Neu eingegangen - Antwortziel innerhalb 24h.</p>',
  ].join('\n');
  const salesText = [
    `Neuer Lead eingegangen (${formLabel})`,
    '',
    ...rows.map(([label, value]) => `${label}: ${value}`),
    ...(fileRows.length > 0
      ? ['', 'Datei-Download:', ...fileRows.map(({ link, href }) => `- ${link.name}: ${href ?? link.path}`)]
      : []),
    '',
    `Lead-ID: ${record.id}`,
    `Gespeichert in R2: ${storageKey}`,
  ].join('\n');

  const name = record.fields.name;
  const customerHtml = [
    `<p>Guten Tag ${escapeHtml(name)},</p>`,
    '<p>vielen Dank für Ihre Anfrage bei <strong>3D-WINDT</strong>. Wir haben Ihre Angaben erhalten und starten jetzt die technische Prüfung.</p>',
    '<p><strong>Nächste Schritte:</strong></p>',
    `<ol>${SALES_STEPS.map((step) => `<li>${escapeHtml(step)}</li>`).join('')}</ol>`,
    '<p>Bei Rückfragen antworten Sie einfach auf diese E-Mail.</p>',
    '<p>Freundliche Grüße<br />3D-WINDT</p>',
  ].join('\n');
  const customerText = [
    `Guten Tag ${name},`,
    '',
    'vielen Dank für Ihre Anfrage bei 3D-WINDT. Wir haben Ihre Angaben erhalten und starten jetzt die technische Prüfung.',
    '',
    'Nächste Schritte:',
    ...SALES_STEPS.map((step, index) => `${index + 1}. ${step}`),
    '',
    'Bei Rückfragen antworten Sie einfach auf diese E-Mail.',
    '',
    'Freundliche Grüße',
    '3D-WINDT',
  ].join('\n');

  return {
    sales: {
      from: mail.from,
      to: mail.to,
      replyTo: record.fields.email,
      subject: `Neuer Lead (${formLabel}) - ${name}`,
      html: salesHtml,
      text: salesText,
    },
    customer: {
      from: mail.from,
      to: record.fields.email,
      subject: 'Eingangsbestätigung: Ihre Anfrage bei 3D-WINDT',
      html: customerHtml,
      text: customerText,
    },
  };
}

async function notify(record: LeadRecord, storageKey: string, deps: LeadDeps): Promise<boolean> {
  const mail = readLeadMailConfig(deps.env);
  if (!mail.ok) {
    console.error(`[lead] ${mail.problem} Lead ${record.id} stored at ${storageKey} without notification.`);
    return false;
  }
  const origin = readSiteOrigin(deps.env);
  if (!origin.ok) {
    console.error(`[lead] ${origin.problem} File links in the sales mail are relative.`);
  }
  const { sales, customer } = buildLeadMails(record, storageKey, mail.value, origin.ok ? origin.value : null);
  const [salesResult, customerResult] = await Promise.allSettled([
    deps.sendMail(sales, mail.value.resendApiKey, `lead-${record.id}-sales`),
    deps.sendMail(customer, mail.value.resendApiKey, `lead-${record.id}-customer`),
  ]);
  if (customerResult.status === 'rejected') {
    console.error(`[lead] Confirmation mail for ${record.id} failed: ${String(customerResult.reason)}`);
  }
  if (salesResult.status === 'rejected') {
    console.error(`[lead] Sales notification for ${record.id} failed (lead is stored at ${storageKey}): ${String(salesResult.reason)}`);
    return false;
  }
  return true;
}

export async function handleLead(request: Request, deps: LeadDeps): Promise<Response> {
  if (request.method !== 'POST') {
    return jsonResponse(405, { error: 'Methode nicht erlaubt.' }, { Allow: 'POST' });
  }
  if (!isSameOriginRequest(request.url, request.headers.get('origin'))) {
    return jsonResponse(403, { error: 'Anfrage nicht erlaubt.' });
  }
  const parsed = await parseBody(request);
  if (!parsed.ok) {
    return parsed.response;
  }
  const { values, fileLinks, nativeForm } = parsed.raw;

  const validation = validateLead(values);
  if (!validation.ok) {
    return jsonResponse(400, { error: validation.error });
  }
  const success = (body: Record<string, unknown>) =>
    nativeForm
      ? new Response(null, {
          status: 303,
          headers: { Location: LEAD_THANK_YOU_PATH[validation.form], 'Cache-Control': 'no-store' },
        })
      : jsonResponse(200, body);

  // Honeypot filled: answer like a success so bots learn nothing, store nothing.
  const honeypot = values[HONEYPOT_FIELD];
  if (typeof honeypot === 'string' && honeypot.trim() !== '') {
    return success({ ok: true });
  }

  const now = deps.now();
  const limited = await enforceRateLimit(deps.kv, RATE_LIMITS.lead, request, now.getTime());
  if (limited) {
    return limited;
  }

  const record: LeadRecord = {
    id: deps.newId(),
    receivedAt: now.toISOString(),
    form: validation.form,
    fields: validation.fields,
    fileLinks: toFileLinks(fileLinks),
    truncatedFields: validation.truncatedFields,
  };
  const storageKey = leadObjectKey(record.id, now);
  try {
    const stored = await deps.bucket.put(storageKey, JSON.stringify(record, null, 2), {
      httpMetadata: { contentType: 'application/json; charset=utf-8' },
      customMetadata: { form: record.form },
    });
    if (!stored) {
      throw new Error('R2 put returned no object.');
    }
  } catch (error) {
    console.error(`[lead] Could not store lead ${record.id}: ${String(error)}`);
    return jsonResponse(502, {
      error: 'Die Anfrage konnte nicht gespeichert werden. Bitte versuchen Sie es erneut oder kontaktieren Sie uns direkt.',
    });
  }

  const notified = await notify(record, storageKey, deps);
  return success({ ok: true, id: record.id, notified });
}
